--- 
# log_file is optional. Simply leave it undefined to not log to a file
log_file: /Users/masukomi/workspace/octopress_test_site/jekyllmail.log
## Setting debug to true places the script 
## in a debug state, which results in some verbose
## output and overrides delete_after_run
debug: false
blogs: 
- name: my blog name
  active: true
  # you may want to temporarily pause the ingestion 
  # of emails for a specific blog without having 
  # to disable the cron job.
  local_repo: my_blog
    # typically this is a local repo that JekyllMail updates 
    # and pushes to an origin repo, but it can just be a local
    # directory you want JekyllMail to store your files under.
  origin_repo: /home/path/to/my/octopress_blog.git
    # origin_repo could also be me@example.com:path/to/blog.git
    # orign_repo_branch defaults to master
  pop_server: mail.example.com
  pop_user: jekyllmail@example.com
  pop_password: password_here
  secret: jekyllmail
  markup: markdown
  site_url: http://blog.example.com
  commit_after_save: true
  delete_after_run: true
