--- 
blogs: 
- jekyll_repo: /home/username/workspace/jekyll_test_site
  source_dir: /home/username/workspace/jekyll_test_site/source
  pop_server: mail.example.com
  pop_user: jekyllmail@example.com
  pop_password: password_here
  secret: jekyllmail
  markup: markdown
  site_url: http://blog.example.com
  commit_after_save: true
  delete_after_run: true
## Setting debug to true places the script 
## in a debug state, which results in some verbose
## output and overrides delete_after_run
debug: false
